### ISSUE TITLE
Cannot create research note for Wesly's Hammer

### ISSUE THREAD

**Issue by Akkqa** [iwo-strzebonski/ThaumicRevelations#2]
I click the icon and it takes a piece of paper and makes the correct noise but does not give me the research note.

**Expected behavior**
I expected it to give me the research note

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.4.3

**Comment by iwo-strzebonski** [comment]
Oh, I must've forgotten to add aspects to that research...

**Comment by iwo-strzebonski** [comment]
Solved in 0.2.4.4
