### ISSUE TITLE
crash when open server

### ISSUE THREAD

**Issue by ZHENGLOC** [iwo-strzebonski/ThaumicRevelations#3]
**Describe the bug**
crash when open server

**To Reproduce**

open server

 - Minecraft Version: 1.7.10
 - Mod Version: ThaumicRevelations-0.2.4.4

**Additional context**

crash report: https://paste.ubuntu.com/p/xVzyCSjgdV/

**Comment by iwo-strzebonski** [comment]
@ZHENGLOC could you try now with version 0.2.4.5?

**Comment by ZHENGLOC** [comment]
> @ZHENGLOC could you try now with version 0.2.4.5?

can work now
