### ISSUE TITLE
Please add config-- Ability to alter growth of Wardenic Rose

### ISSUE THREAD

**Issue by Leofric118** [iwo-strzebonski/ThaumicRevelations#4]
I Like my games to be balanced so I'd appreciate it if the wardenic rose didn't grow so fast.

Please add some way of altering the growth speed , like a config file , so one can make it balanced to their modpack.

**Comment by iwo-strzebonski** [comment]
I'll add a config file in the following update

**Comment by Leofric118** [comment]
Thanks!

**Comment by iwo-strzebonski** [comment]
@Leofric118 could you please check if the growth speed can be altered via config file?

**Comment by Leofric118** [comment]
Sure, but it's midnight right now. I'll check first thing in the morning.

**Comment by Leofric118** [comment]
It seems to be working. I'm currently testing the config.

**Comment by Leofric118** [comment]
IT WORKS! TYSM!

**Comment by Leofric118** [comment]
Setting it to less than 1 reverts it back to 1. On 1 it takes about 7 minutes to grow. On 10 an hour has passed since I planted them and their not fully grown yet
